#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

#require "net/ddex/xml/v2011/amep/v11/key_info"
require "org/w3/v2000/v09/xmldsig/signature_value"
require "org/w3/v2000/v09/xmldsig/signed_info"

module Net module Ddex module Xml module V2011 module Amep module V11  # :nodoc: all

class Net::Ddex::Xml::V2011::Amep::V11::DdexDigitalSignature < Element
  include ROXML


  xml_name "ns3:DdexDigitalSignature"

      xml_accessor :signed_info, :as => Org::W3::V2000::V09::Xmldsig::SignedInfo, :from => "SignedInfo", :required => true
      xml_accessor :signature_value, :as => Org::W3::V2000::V09::Xmldsig::SignatureValue, :from => "SignatureValue", :required => true
#      xml_accessor :key_info, :as => Net::Ddex::Xml::V2011::Amep::V11::KeyInfo, :from => "KeyInfo", :required => true


  
      xml_accessor :id, :from => "@Id", :required => false
    
  

end

end end end end end end
