#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2011/amep/v11/ddex_digital_signature"
require "net/ddex/xml/v20110120/ddexc/hash_sum"
require "net/ddex/xml/v20110120/ddexc/messaging_party"

module Net module Ddex module Xml module V2011 module Amep module V11  # :nodoc: all

class Net::Ddex::Xml::V2011::Amep::V11::FtpMessageHeader < Element
  include ROXML


  xml_name "ns3:FtpMessageHeader"

      xml_accessor :message_sender, :as => Net::Ddex::Xml::V20110120::Ddexc::MessagingParty, :from => "MessageSender", :required => true
      xml_accessor :message_recipient, :as => Net::Ddex::Xml::V20110120::Ddexc::MessagingParty, :from => "MessageRecipient", :required => true
      xml_accessor :message_created_date_time, :as => DateTime, :from => "MessageCreatedDateTime", :required => true
      xml_accessor :signature, :as => Net::Ddex::Xml::V2011::Amep::V11::DdexDigitalSignature, :from => "Signature", :required => false
      xml_accessor :hash_sum, :as => Net::Ddex::Xml::V20110120::Ddexc::HashSum, :from => "HashSum", :required => false


  

end

end end end end end end
