#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2011/amep/v11/ftp_message_header"
require "net/ddex/xml/v2011/amep/v11/received_file"

module Net module Ddex module Xml module V2011 module Amep module V11  # :nodoc: all

class Net::Ddex::Xml::V2011::Amep::V11::FtpAcknowledgementMessage < Element
  include ROXML

    setns "ns3", "http://ddex.net/xml/2011/amep/11"

  xml_name "ns3:FtpAcknowledgementMessage"

      xml_accessor :message_header, :as => Net::Ddex::Xml::V2011::Amep::V11::FtpMessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :received_files, :as => [Net::Ddex::Xml::V2011::Amep::V11::ReceivedFile], :from => "ReceivedFile", :required => true
      xml_accessor :error_text, :from => "ErrorText", :required => false


  
      xml_accessor :message_version_id, :from => "@MessageVersionId", :required => true
    
  

end

end end end end end end
