#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "java/io/serializable"

module Net module Ddex module Xml module V2011 module Amep module V11  # :nodoc: all

class Net::Ddex::Xml::V2011::Amep::V11::KeyInfo < Element
  include ROXML


  xml_name "ns3:KeyInfo"

      xml_accessor :contents, :as => [Java::Io::Serializable], :from => "X509Data", :required => true

    xml_accessor :value, :from => ".", :required => false

  
      xml_accessor :id, :from => "@Id", :required => false
    
  

end

end end end end end end
