#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2011/amep/v11/ddex_digital_signature"
require "net/ddex/xml/v20110120/ddexc/hash_sum"

module Net module Ddex module Xml module V2011 module Amep module V11  # :nodoc: all

class Net::Ddex::Xml::V2011::Amep::V11::ReceivedFile < Element
  include ROXML


  xml_name "ns3:ReceivedFile"

      xml_accessor :file_name, :from => "FileName", :required => true
      xml_accessor :file_status, :from => "FileStatus", :required => true
      xml_accessor :signature, :as => Net::Ddex::Xml::V2011::Amep::V11::DdexDigitalSignature, :from => "Signature", :required => false
      xml_accessor :hash_sum, :as => Net::Ddex::Xml::V20110120::Ddexc::HashSum, :from => "HashSum", :required => false


  

end

end end end end end end
