#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2011/amep/v11/ws_acknowledgement_message"
require "net/ddex/xml/v20110120/ddexc/file"

module Net module Ddex module Xml module V2011 module Amep module V11  # :nodoc: all

class Net::Ddex::Xml::V2011::Amep::V11::WsBatchConfirmationMessage < Net::Ddex::Xml::V2011::Amep::V11::WsAcknowledgementMessage
  include ROXML

    setns "ns3", "http://ddex.net/xml/2011/amep/11"

  xml_name "ns3:WsBatchConfirmationMessage"

      xml_accessor :batch_transfer_status, :from => "BatchTransferStatus", :required => true
      xml_accessor :not_transferred_files, :as => [Net::Ddex::Xml::V20110120::Ddexc::File], :from => "NotTransferredFile", :required => false


  

end

end end end end end end
