#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module Net module Ddex module Xml module V2011 module Amep module V11  # :nodoc: all

class Net::Ddex::Xml::V2011::Amep::V11::X509Data < Element
  include ROXML


  xml_name "ns3:X509Data"

      xml_accessor :x509_issuer_serials_and_x509_skis_and_x509_subject_names, :as => [], :from => "x509IssuerSerialsAndX509SKISAndX509SubjectNames", :required => false


  

end

end end end end end end
