#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/echo/v11/delivery_message"
require "net/ddex/xml/v20110120/ddexc/name"
require "net/ddex/xml/v20110120/ddexc/reference_title"
require "net/ddex/xml/v20110120/ddexc/release_id"
require "net/ddex/xml/v20110120/ddexc/release_type"

module DDEX module ECHO module V11  # :nodoc: all

class DDEX::ECHO::V11::DeliveredRelease < Element
  include ROXML


  xml_name "ns4:DeliveredRelease"

      xml_accessor :release_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseId], :from => "ReleaseId", :required => true
      xml_accessor :release_type, :as => Net::Ddex::Xml::V20110120::Ddexc::ReleaseType, :from => "ReleaseType", :required => true
      xml_accessor :display_artist_names, :as => [Net::Ddex::Xml::V20110120::Ddexc::Name], :from => "DisplayArtistName", :required => true
      xml_accessor :reference_title, :as => Net::Ddex::Xml::V20110120::Ddexc::ReferenceTitle, :from => "ReferenceTitle", :required => true
      xml_accessor :delivery_message, :as => DDEX::ECHO::V11::DeliveryMessage, :from => "DeliveryMessage", :required => false


  

end

end end end
