#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/hash_sum"
require "net/ddex/xml/v20110120/ddexc/release_id"

module DDEX module ECHO module V11  # :nodoc: all

class DDEX::ECHO::V11::MessageInBatch < Element
  include ROXML


  xml_name "ns4:MessageInBatch"

      xml_accessor :message_type, :from => "MessageType", :required => true
      xml_accessor :message_id, :from => "MessageId", :required => true
      xml_accessor :url, :from => "URL", :required => true
      xml_accessor :included_release_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseId], :from => "IncludedReleaseId", :required => true
      xml_accessor :signature, :from => "Signature", :required => false
      xml_accessor :hash_sum, :as => Net::Ddex::Xml::V20110120::Ddexc::HashSum, :from => "HashSum", :required => false


  

end

end end end
