#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/echo/v11/release_summary"
require "net/ddex/xml/v2011/amep/v11/ws_message_header"
require "net/ddex/xml/v20110120/ddexc/order_type"
require "net/ddex/xml/v20110120/ddexc/party_descriptor"
require "net/ddex/xml/v20110120/ddexc/period"

module DDEX module ECHO module V11  # :nodoc: all

class DDEX::ECHO::V11::OrderedReleaseInQueueRequestMessage < Element
  include ROXML

    setns "ns4", "http://ddex.net/xml/2011/echo/11"

  xml_name "ns4:OrderedReleaseInQueueRequestMessage"

      xml_accessor :message_header, :as => Net::Ddex::Xml::V2011::Amep::V11::WsMessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :dsp, :as => Net::Ddex::Xml::V20110120::Ddexc::PartyDescriptor, :from => "DSP", :required => true
      xml_accessor :order_type, :as => Net::Ddex::Xml::V20110120::Ddexc::OrderType, :from => "OrderType", :required => false
      xml_accessor :releases, :as => [DDEX::ECHO::V11::ReleaseSummary], :from => "Release", :required => false
      xml_accessor :excluded_territory_codes, :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :from => "TerritoryCode", :required => false
      xml_accessor :period, :as => Net::Ddex::Xml::V20110120::Ddexc::Period, :from => "Period", :required => false


  
      xml_accessor :message_version_id, :from => "@MessageVersionId", :required => true
    
  

end

end end end
