#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/new_release_message"
require "net/ddex/xml/v2011/amep/v11/ws_message_header"
require "net/ddex/xml/v20110120/ddexc/release_id"

module DDEX module ECHO module V11  # :nodoc: all

class DDEX::ECHO::V11::ReleaseAvailabilityMessage < Element
  include ROXML

    setns "ns4", "http://ddex.net/xml/2011/echo/11"

  xml_name "ns4:ReleaseAvailabilityMessage"

      xml_accessor :message_header, :as => Net::Ddex::Xml::V2011::Amep::V11::WsMessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :release_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseId], :from => "ReleaseId", :required => true
      xml_accessor :new_release_message, :as => DDEX::ERN::V32::NewReleaseMessage, :from => "ns1:NewReleaseMessage", :required => true


  
      xml_accessor :message_version_id, :from => "@MessageVersionId", :required => true
    
  

end

end end end
