#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/echo/v11/ws_acknowledgement"
require "net/ddex/xml/v20110120/ddexc/event_date"
require "net/ddex/xml/v20110120/ddexc/supply_chain_status"

module DDEX module ECHO module V11  # :nodoc: all

class DDEX::ECHO::V11::ReleaseSupplyChainStatusResponseMessage < DDEX::ECHO::V11::WsAcknowledgement
  include ROXML

    setns "ns4", "http://ddex.net/xml/2011/echo/11"

  xml_name "ns4:ReleaseSupplyChainStatusResponseMessage"

      xml_accessor :status, :as => Net::Ddex::Xml::V20110120::Ddexc::SupplyChainStatus, :from => "Status", :required => true
      xml_accessor :status_change_date, :as => Net::Ddex::Xml::V20110120::Ddexc::EventDate, :from => "StatusChangeDate", :required => false


  
      xml_accessor :message_version_id, :from => "@MessageVersionId", :required => true
    
  

end

end end end
