#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2011/amep/v11/ws_message_header"
require "net/ddex/xml/v20110120/ddexc/file"
require "net/ddex/xml/v20110120/ddexc/report_format"
require "net/ddex/xml/v20110120/ddexc/report_type"

module DDEX module ECHO module V11  # :nodoc: all

class DDEX::ECHO::V11::ReportDeliveryMessage < Element
  include ROXML

    setns "ns4", "http://ddex.net/xml/2011/echo/11"

  xml_name "ns4:ReportDeliveryMessage"

      xml_accessor :message_header, :as => Net::Ddex::Xml::V2011::Amep::V11::WsMessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :ticket_id, :from => "TicketId", :required => true
      xml_accessor :report_type, :as => Net::Ddex::Xml::V20110120::Ddexc::ReportType, :from => "ReportType", :required => true
      xml_accessor :report_format, :as => Net::Ddex::Xml::V20110120::Ddexc::ReportFormat, :from => "ReportFormat", :required => true
      xml_accessor :file, :as => Net::Ddex::Xml::V20110120::Ddexc::File, :from => "File", :required => true


  
      xml_accessor :message_version_id, :from => "@MessageVersionId", :required => true
    
  

end

end end end
