#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/messaging_party"
require "net/ddex/xml/v20110120/ddexc/period"

module DDEX module ECHO module V11  # :nodoc: all

class DDEX::ECHO::V11::ReportMessageHeader < Element
  include ROXML


  xml_name "ns4:ReportMessageHeader"

      xml_accessor :message_sender, :as => Net::Ddex::Xml::V20110120::Ddexc::MessagingParty, :from => "MessageSender", :required => true
      xml_accessor :message_recipient, :as => Net::Ddex::Xml::V20110120::Ddexc::MessagingParty, :from => "MessageRecipient", :required => true
      xml_accessor :test_flag?, :from => "IsTestFlag", :required => false
      xml_accessor :ticket_id, :from => "TicketId", :required => true
      xml_accessor :message_created_date_time, :as => DateTime, :from => "MessageCreatedDateTime", :required => true
      xml_accessor :period_covered, :as => Net::Ddex::Xml::V20110120::Ddexc::Period, :from => "PeriodCovered", :required => true


  

end

end end end
