#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2011/amep/v11/ws_message_header"
require "net/ddex/xml/v20110120/ddexc/event_date_time"
require "net/ddex/xml/v20110120/ddexc/party_descriptor"
require "net/ddex/xml/v20110120/ddexc/release_id"
require "net/ddex/xml/v20110120/ddexc/supply_chain_status"

module DDEX module ECHO module V11  # :nodoc: all

class DDEX::ECHO::V11::SupplyChainStatusMessage < Element
  include ROXML

    setns "ns4", "http://ddex.net/xml/2011/echo/11"

  xml_name "ns4:SupplyChainStatusMessage"

      xml_accessor :message_header, :as => Net::Ddex::Xml::V2011::Amep::V11::WsMessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :dsp, :as => Net::Ddex::Xml::V20110120::Ddexc::PartyDescriptor, :from => "DSP", :required => true
      xml_accessor :release_id, :as => Net::Ddex::Xml::V20110120::Ddexc::ReleaseId, :from => "ReleaseId", :required => true
      xml_accessor :status, :as => Net::Ddex::Xml::V20110120::Ddexc::SupplyChainStatus, :from => "Status", :required => true
      xml_accessor :status_change_date_time, :as => Net::Ddex::Xml::V20110120::Ddexc::EventDateTime, :from => "StatusChangeDateTime", :required => false


  
      xml_accessor :message_version_id, :from => "@MessageVersionId", :required => true
    
  

end

end end end
