#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2011/amep/v11/ws_message_header"

module DDEX module ECHO module V11  # :nodoc: all

class DDEX::ECHO::V11::WsAcknowledgement < Element
  include ROXML


  xml_name "ns4:WsAcknowledgement"

      xml_accessor :message_header, :as => Net::Ddex::Xml::V2011::Amep::V11::WsMessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :acknowledged_ws_message_id, :from => "AcknowledgedWsMessageId", :required => true
      xml_accessor :received_ws_message_status, :from => "ReceivedWsMessageStatus", :required => true
      xml_accessor :error_text, :from => "ErrorText", :required => false


  

end

end end end
