#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:10 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::CollectionResourceReferenceList < Element
  include ROXML


  xml_name "ns1:CollectionResourceReferenceList"

      xml_accessor :collection_resource_references, :as => [], :from => "CollectionResourceReference", :required => false


  

end

end end end
