#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:10 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/character"
require "net/ddex/xml/v20100712/ddexc/collection_details_by_territory"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::CollectionDetailsByTerritory < Net::Ddex::Xml::V20100712::Ddexc::CollectionDetailsByTerritory
  include ROXML


  xml_name "ns1:CollectionDetailsByTerritory"

      xml_accessor :characters, :as => [Net::Ddex::Xml::V20100712::Ddexc::Character], :from => "Character", :required => false


  

end

end end end
