#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:10 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/c_line"
require "net/ddex/xml/v20100712/ddexc/character"
require "net/ddex/xml/v20100712/ddexc/cue_creation_reference"
require "net/ddex/xml/v20100712/ddexc/cue_origin"
require "net/ddex/xml/v20100712/ddexc/cue_theme_type"
require "net/ddex/xml/v20100712/ddexc/cue_use_type"
require "net/ddex/xml/v20100712/ddexc/cue_visual_perception_type"
require "net/ddex/xml/v20100712/ddexc/cue_vocal_type"
require "net/ddex/xml/v20100712/ddexc/p_line"
require "net/ddex/xml/v20100712/ddexc/resource_contributor"
require "net/ddex/xml/v20100712/ddexc/title"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::Cue < Element
  include ROXML


  xml_name "ns1:Cue"

      xml_accessor :cue_use_type, :as => Net::Ddex::Xml::V20100712::Ddexc::CueUseType, :from => "CueUseType", :required => false
      xml_accessor :cue_theme_type, :as => Net::Ddex::Xml::V20100712::Ddexc::CueThemeType, :from => "CueThemeType", :required => false
      xml_accessor :cue_vocal_type, :as => Net::Ddex::Xml::V20100712::Ddexc::CueVocalType, :from => "CueVocalType", :required => false
      xml_accessor :dance?, :from => "IsDance", :required => false
      xml_accessor :cue_visual_perception_type, :as => Net::Ddex::Xml::V20100712::Ddexc::CueVisualPerceptionType, :from => "CueVisualPerceptionType", :required => false
      xml_accessor :cue_origin, :as => Net::Ddex::Xml::V20100712::Ddexc::CueOrigin, :from => "CueOrigin", :required => false
      xml_accessor :referenced_creation_type, :from => "ReferencedCreationType", :required => false
      xml_accessor :referenced_creation_titles, :as => [Net::Ddex::Xml::V20100712::Ddexc::Title], :from => "ReferencedCreationTitle", :required => false
      xml_accessor :referenced_creation_contributors, :as => [Net::Ddex::Xml::V20100712::Ddexc::ResourceContributor], :from => "ReferencedCreationContributor", :required => false
      xml_accessor :referenced_creation_characters, :as => [Net::Ddex::Xml::V20100712::Ddexc::Character], :from => "ReferencedCreationCharacter", :required => false
      xml_accessor :cue_creation_references, :as => [Net::Ddex::Xml::V20100712::Ddexc::CueCreationReference], :from => "CueCreationReference", :required => false
      xml_accessor :has_musical_content?, :from => "HasMusicalContent", :required => false
      xml_accessor :start_time, :from => "StartTime", :required => false
      xml_accessor :duration, :from => "Duration", :required => false
      xml_accessor :end_time, :from => "EndTime", :required => false
      xml_accessor :p_lines, :as => [Net::Ddex::Xml::V20100712::Ddexc::PLine], :from => "PLine", :required => false
      xml_accessor :c_lines, :as => [Net::Ddex::Xml::V20100712::Ddexc::CLine], :from => "CLine", :required => false


  

end

end end end
