#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:10 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/cue"
require "net/ddex/xml/v20100712/ddexc/cue_sheet_type"
require "net/ddex/xml/v20100712/ddexc/proprietary_id"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::CueSheet < Element
  include ROXML


  xml_name "ns1:CueSheet"

      xml_accessor :cue_sheet_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::ProprietaryId], :from => "CueSheetId", :required => false
      xml_accessor :cue_sheet_reference, :from => "CueSheetReference", :required => true
      xml_accessor :cue_sheet_type, :as => Net::Ddex::Xml::V20100712::Ddexc::CueSheetType, :from => "CueSheetType", :required => true
      xml_accessor :cues, :as => [DDEX::ERN::V32::Cue], :from => "Cue", :required => true


  

end

end end end
