#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:10 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/physical_returns"
require "ddex/ern/v32/related_release_offer_set"
require "net/ddex/xml/v20100712/ddexc/commercial_model_type"
require "net/ddex/xml/v20100712/ddexc/consumer_rental_period"
require "net/ddex/xml/v20100712/ddexc/dsp"
require "net/ddex/xml/v20100712/ddexc/event_date"
require "net/ddex/xml/v20100712/ddexc/period"
require "net/ddex/xml/v20100712/ddexc/price_information"
require "net/ddex/xml/v20100712/ddexc/promotional_code"
require "net/ddex/xml/v20100712/ddexc/usage"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::DealTerms < Element
  include ROXML


  xml_name "ns1:DealTerms"

      xml_accessor :commercial_model_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::CommercialModelType], :from => "CommercialModelType", :required => false
      xml_accessor :take_down?, :from => "TakeDown", :required => false
      xml_accessor :all_deals_cancelled?, :from => "AllDealsCancelled", :required => false
      xml_accessor :usages, :as => [Net::Ddex::Xml::V20100712::Ddexc::Usage], :from => "Usage", :required => false
      xml_accessor :excluded_territory_codes, :as => [], :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :as => [], :from => "TerritoryCode", :required => false
      xml_accessor :excluded_distribution_channels, :as => [Net::Ddex::Xml::V20100712::Ddexc::DSP], :from => "ExcludedDistributionChannel", :required => false
      xml_accessor :distribution_channels, :as => [Net::Ddex::Xml::V20100712::Ddexc::DSP], :from => "DistributionChannel", :required => false
      xml_accessor :price_information, :as => Net::Ddex::Xml::V20100712::Ddexc::PriceInformation, :from => "PriceInformation", :required => false
      xml_accessor :promotional_code, :as => Net::Ddex::Xml::V20100712::Ddexc::PromotionalCode, :from => "PromotionalCode", :required => false
      xml_accessor :promotional?, :from => "IsPromotional", :required => false
      xml_accessor :validity_periods, :as => [Net::Ddex::Xml::V20100712::Ddexc::Period], :from => "ValidityPeriod", :required => true
      xml_accessor :consumer_rental_period, :as => Net::Ddex::Xml::V20100712::Ddexc::ConsumerRentalPeriod, :from => "ConsumerRentalPeriod", :required => false
      xml_accessor :pre_order_release_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "PreOrderReleaseDate", :required => false
      xml_accessor :exclusive?, :from => "IsExclusive", :required => false
      xml_accessor :related_release_offer_sets, :as => [DDEX::ERN::V32::RelatedReleaseOfferSet], :from => "RelatedReleaseOfferSet", :required => false
      xml_accessor :physical_returns, :as => DDEX::ERN::V32::PhysicalReturns, :from => "PhysicalReturns", :required => false
      xml_accessor :number_of_products_per_carton, :as => Integer, :from => "NumberOfProductsPerCarton", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
