#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:10 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/midi_details_by_territory"
require "net/ddex/xml/v20100712/ddexc/description"
require "net/ddex/xml/v20100712/ddexc/event_date"
require "net/ddex/xml/v20100712/ddexc/midi_id"
require "net/ddex/xml/v20100712/ddexc/midi_type"
require "net/ddex/xml/v20100712/ddexc/musical_work_id"
require "net/ddex/xml/v20100712/ddexc/reference_title"
require "net/ddex/xml/v20100712/ddexc/resource_contained_resource_reference_list"
require "net/ddex/xml/v20100712/ddexc/resource_musical_work_reference_list"
require "net/ddex/xml/v20100712/ddexc/rights_agreement_id"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::MIDI < Element
  include ROXML


  xml_name "ns1:MIDI"

      xml_accessor :midi_type, :as => Net::Ddex::Xml::V20100712::Ddexc::MidiType, :from => "MidiType", :required => false
      xml_accessor :artist_related?, :from => "IsArtistRelated", :required => false
      xml_accessor :midi_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::MidiId], :from => "MidiId", :required => true
      xml_accessor :indirect_midi_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::MusicalWorkId], :from => "IndirectMidiId", :required => false
      xml_accessor :resource_reference, :from => "ResourceReference", :required => true
      xml_accessor :reference_title, :as => Net::Ddex::Xml::V20100712::Ddexc::ReferenceTitle, :from => "ReferenceTitle", :required => true
      xml_accessor :instrumentation_description, :as => Net::Ddex::Xml::V20100712::Ddexc::Description, :from => "InstrumentationDescription", :required => false
      xml_accessor :medley?, :from => "IsMedley", :required => false
      xml_accessor :potpourri?, :from => "IsPotpourri", :required => false
      xml_accessor :instrumental?, :from => "IsInstrumental", :required => false
      xml_accessor :background?, :from => "IsBackground", :required => false
      xml_accessor :hidden_resource?, :from => "IsHiddenResource", :required => false
      xml_accessor :bonus_resource?, :from => "IsBonusResource", :required => false
      xml_accessor :computer_generated?, :from => "IsComputerGenerated", :required => false
      xml_accessor :no_silence_before?, :from => "NoSilenceBefore", :required => false
      xml_accessor :no_silence_after?, :from => "NoSilenceAfter", :required => false
      xml_accessor :language_of_performance, :from => "LanguageOfPerformance", :required => false
      xml_accessor :duration, :from => "Duration", :required => true
      xml_accessor :rights_agreement_id, :as => Net::Ddex::Xml::V20100712::Ddexc::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :resource_musical_work_reference_list, :as => Net::Ddex::Xml::V20100712::Ddexc::ResourceMusicalWorkReferenceList, :from => "ResourceMusicalWorkReferenceList", :required => false
      xml_accessor :resource_contained_resource_reference_list, :as => Net::Ddex::Xml::V20100712::Ddexc::ResourceContainedResourceReferenceList, :from => "ResourceContainedResourceReferenceList", :required => false
      xml_accessor :creation_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "CreationDate", :required => false
      xml_accessor :mastered_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "MasteredDate", :required => false
      xml_accessor :midi_details_by_territories, :as => [DDEX::ERN::V32::MidiDetailsByTerritory], :from => "MidiDetailsByTerritory", :required => true


  
      xml_accessor :updated?, :from => "@IsUpdated", :required => false
    
  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
