#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/resource_group"
require "net/ddex/xml/v20100712/ddexc/av_rating"
require "net/ddex/xml/v20100712/ddexc/character"
require "net/ddex/xml/v20100712/ddexc/comment"
require "net/ddex/xml/v20100712/ddexc/description"
require "net/ddex/xml/v20100712/ddexc/event_date"
require "net/ddex/xml/v20100712/ddexc/file"
require "net/ddex/xml/v20100712/ddexc/genre"
require "net/ddex/xml/v20100712/ddexc/keywords"
require "net/ddex/xml/v20100712/ddexc/parental_warning_type"
require "net/ddex/xml/v20100712/ddexc/release_details_by_territory"
require "net/ddex/xml/v20100712/ddexc/synopsis"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::ReleaseDetailsByTerritory < Net::Ddex::Xml::V20100712::Ddexc::ReleaseDetailsByTerritory
  include ROXML


  xml_name "ns1:ReleaseDetailsByTerritory"

      xml_accessor :parental_warning_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::ParentalWarningType], :from => "ParentalWarningType", :required => false
      xml_accessor :av_ratings, :as => [Net::Ddex::Xml::V20100712::Ddexc::AvRating], :from => "AvRating", :required => false
      xml_accessor :marketing_comment, :as => Net::Ddex::Xml::V20100712::Ddexc::Comment, :from => "MarketingComment", :required => false
      xml_accessor :resource_groups, :as => [DDEX::ERN::V32::ResourceGroup], :from => "ResourceGroup", :required => false
      xml_accessor :genres, :as => [Net::Ddex::Xml::V20100712::Ddexc::Genre], :from => "Genre", :required => false
      xml_accessor :original_release_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "OriginalReleaseDate", :required => false
      xml_accessor :original_digital_release_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "OriginalDigitalReleaseDate", :required => false
      xml_accessor :files, :as => [Net::Ddex::Xml::V20100712::Ddexc::File], :from => "File", :required => false
      xml_accessor :file_availability_descriptions, :as => [Net::Ddex::Xml::V20100712::Ddexc::Description], :from => "FileAvailabilityDescription", :required => false
      xml_accessor :keywords, :as => Net::Ddex::Xml::V20100712::Ddexc::Keywords, :from => "Keywords", :required => false
      xml_accessor :synopsis, :as => Net::Ddex::Xml::V20100712::Ddexc::Synopsis, :from => "Synopsis", :required => false
      xml_accessor :characters, :as => [Net::Ddex::Xml::V20100712::Ddexc::Character], :from => "Character", :required => false
      xml_accessor :number_of_units_per_physical_release, :as => Integer, :from => "NumberOfUnitsPerPhysicalRelease", :required => false


  

end

end end end
