#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/resource_group"
require "ddex/ern/v32/resource_group_content_item"
require "net/ddex/xml/v20100712/ddexc/display_artist"
require "net/ddex/xml/v20100712/ddexc/indirect_resource_contributor"
require "net/ddex/xml/v20100712/ddexc/resource_contributor"
require "net/ddex/xml/v20100712/ddexc/resource_group_resource_reference_list"
require "net/ddex/xml/v20100712/ddexc/title"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::ResourceGroup < Element
  include ROXML


  xml_name "ns1:ResourceGroup"

      xml_accessor :titles, :as => [Net::Ddex::Xml::V20100712::Ddexc::Title], :from => "Title", :required => false
      xml_accessor :sequence_number, :as => Integer, :from => "SequenceNumber", :required => false
      xml_accessor :display_artists, :as => [Net::Ddex::Xml::V20100712::Ddexc::DisplayArtist], :from => "DisplayArtist", :required => false
      xml_accessor :resource_contributors, :as => [Net::Ddex::Xml::V20100712::Ddexc::ResourceContributor], :from => "ResourceContributor", :required => false
      xml_accessor :indirect_resource_contributors, :as => [Net::Ddex::Xml::V20100712::Ddexc::IndirectResourceContributor], :from => "IndirectResourceContributor", :required => false
      xml_accessor :resource_groups, :as => [DDEX::ERN::V32::ResourceGroup], :from => "ResourceGroup", :required => false
      xml_accessor :resource_group_resource_reference_list, :as => Net::Ddex::Xml::V20100712::Ddexc::ResourceGroupResourceReferenceList, :from => "ResourceGroupResourceReferenceList", :required => false
      xml_accessor :resource_group_content_items, :as => [DDEX::ERN::V32::ResourceGroupContentItem], :from => "ResourceGroupContentItem", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
