#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/release_id"
require "net/ddex/xml/v20100712/ddexc/resource_id"
require "net/ddex/xml/v20100712/ddexc/usage"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::ResourceUsage < Element
  include ROXML


  xml_name "ns1:ResourceUsage"

      xml_accessor :deal_resource_references, :as => [], :from => "DealResourceReference", :required => false
      xml_accessor :release_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReleaseId], :from => "ReleaseId", :required => false
      xml_accessor :resource_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::ResourceId], :from => "ResourceId", :required => false
      xml_accessor :usages, :as => [Net::Ddex::Xml::V20100712::Ddexc::Usage], :from => "Usage", :required => true


  

end

end end end
