#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/technical_sheet_music_details"
require "net/ddex/xml/v20100712/ddexc/fulfillment_date"
require "net/ddex/xml/v20100712/ddexc/genre"
require "net/ddex/xml/v20100712/ddexc/parental_warning_type"
require "net/ddex/xml/v20100712/ddexc/sheet_music_details_by_territory"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::SheetMusicDetailsByTerritory < Net::Ddex::Xml::V20100712::Ddexc::SheetMusicDetailsByTerritory
  include ROXML


  xml_name "ns1:SheetMusicDetailsByTerritory"

      xml_accessor :fulfillment_date, :as => Net::Ddex::Xml::V20100712::Ddexc::FulfillmentDate, :from => "FulfillmentDate", :required => false
      xml_accessor :genres, :as => [Net::Ddex::Xml::V20100712::Ddexc::Genre], :from => "Genre", :required => false
      xml_accessor :parental_warning_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::ParentalWarningType], :from => "ParentalWarningType", :required => false
      xml_accessor :technical_sheet_music_details, :as => [DDEX::ERN::V32::TechnicalSheetMusicDetails], :from => "TechnicalSheetMusicDetails", :required => false


  

end

end end end
