#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/description"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::SoundRecordingPreviewDetails < Element
  include ROXML


  xml_name "ns1:SoundRecordingPreviewDetails"

      xml_accessor :part_type, :as => Net::Ddex::Xml::V20100712::Ddexc::Description, :from => "PartType", :required => false
      xml_accessor :start_point, :as => Float, :from => "StartPoint", :required => false
      xml_accessor :end_point, :as => Float, :from => "EndPoint", :required => false
      xml_accessor :duration, :from => "Duration", :required => false
      xml_accessor :top_left_corner, :as => Float, :from => "TopLeftCorner", :required => false
      xml_accessor :bottom_right_corner, :as => Float, :from => "BottomRightCorner", :required => false
      xml_accessor :expression_type, :from => "ExpressionType", :required => true


  

end

end end end
