#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/preview_details"
require "net/ddex/xml/v20100712/ddexc/description"
require "net/ddex/xml/v20100712/ddexc/drm_platform_type"
require "net/ddex/xml/v20100712/ddexc/file"
require "net/ddex/xml/v20100712/ddexc/fulfillment_date"
require "net/ddex/xml/v20100712/ddexc/operating_system_type"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::TechnicalSoftwareDetails < Element
  include ROXML


  xml_name "ns1:TechnicalSoftwareDetails"

      xml_accessor :technical_resource_details_reference, :from => "TechnicalResourceDetailsReference", :required => true
      xml_accessor :drm_platform_type, :as => Net::Ddex::Xml::V20100712::Ddexc::DrmPlatformType, :from => "DrmPlatformType", :required => false
      xml_accessor :operating_system_type, :as => Net::Ddex::Xml::V20100712::Ddexc::OperatingSystemType, :from => "OperatingSystemType", :required => false
      xml_accessor :preview?, :from => "IsPreview", :required => false
      xml_accessor :preview_details, :as => DDEX::ERN::V32::PreviewDetails, :from => "PreviewDetails", :required => false
      xml_accessor :fulfillment_date, :as => Net::Ddex::Xml::V20100712::Ddexc::FulfillmentDate, :from => "FulfillmentDate", :required => false
      xml_accessor :files, :as => [Net::Ddex::Xml::V20100712::Ddexc::File], :from => "File", :required => false
      xml_accessor :file_availability_descriptions, :as => [Net::Ddex::Xml::V20100712::Ddexc::Description], :from => "FileAvailabilityDescription", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
