#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/sound_recording_preview_details"
require "net/ddex/xml/v20100712/ddexc/audio_codec_type"
require "net/ddex/xml/v20100712/ddexc/bit_rate"
require "net/ddex/xml/v20100712/ddexc/description"
require "net/ddex/xml/v20100712/ddexc/drm_platform_type"
require "net/ddex/xml/v20100712/ddexc/extent"
require "net/ddex/xml/v20100712/ddexc/file"
require "net/ddex/xml/v20100712/ddexc/frame_rate"
require "net/ddex/xml/v20100712/ddexc/fulfillment_date"
require "net/ddex/xml/v20100712/ddexc/sampling_rate"
require "net/ddex/xml/v20100712/ddexc/video_codec_type"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::TechnicalVideoDetails < Element
  include ROXML


  xml_name "ns1:TechnicalVideoDetails"

      xml_accessor :technical_resource_details_reference, :from => "TechnicalResourceDetailsReference", :required => true
      xml_accessor :drm_platform_type, :as => Net::Ddex::Xml::V20100712::Ddexc::DrmPlatformType, :from => "DrmPlatformType", :required => false
      xml_accessor :overall_bit_rate, :as => Net::Ddex::Xml::V20100712::Ddexc::BitRate, :from => "OverallBitRate", :required => false
      xml_accessor :video_codec_type, :as => Net::Ddex::Xml::V20100712::Ddexc::VideoCodecType, :from => "VideoCodecType", :required => false
      xml_accessor :video_bit_rate, :as => Net::Ddex::Xml::V20100712::Ddexc::BitRate, :from => "VideoBitRate", :required => false
      xml_accessor :frame_rate, :as => Net::Ddex::Xml::V20100712::Ddexc::FrameRate, :from => "FrameRate", :required => false
      xml_accessor :image_height, :as => Net::Ddex::Xml::V20100712::Ddexc::Extent, :from => "ImageHeight", :required => false
      xml_accessor :image_width, :as => Net::Ddex::Xml::V20100712::Ddexc::Extent, :from => "ImageWidth", :required => false
      xml_accessor :aspect_ratio, :as => Float, :from => "AspectRatio", :required => false
      xml_accessor :color_depth, :as => Integer, :from => "ColorDepth", :required => false
      xml_accessor :video_definition_type, :from => "VideoDefinitionType", :required => false
      xml_accessor :audio_codec_type, :as => Net::Ddex::Xml::V20100712::Ddexc::AudioCodecType, :from => "AudioCodecType", :required => false
      xml_accessor :audio_bit_rate, :as => Net::Ddex::Xml::V20100712::Ddexc::BitRate, :from => "AudioBitRate", :required => false
      xml_accessor :number_of_audio_channels, :as => Integer, :from => "NumberOfAudioChannels", :required => false
      xml_accessor :audio_sampling_rate, :as => Net::Ddex::Xml::V20100712::Ddexc::SamplingRate, :from => "AudioSamplingRate", :required => false
      xml_accessor :audio_bits_per_sample, :as => Integer, :from => "AudioBitsPerSample", :required => false
      xml_accessor :preview?, :from => "IsPreview", :required => false
      xml_accessor :preview_details, :as => DDEX::ERN::V32::SoundRecordingPreviewDetails, :from => "PreviewDetails", :required => false
      xml_accessor :fulfillment_date, :as => Net::Ddex::Xml::V20100712::Ddexc::FulfillmentDate, :from => "FulfillmentDate", :required => false
      xml_accessor :files, :as => [Net::Ddex::Xml::V20100712::Ddexc::File], :from => "File", :required => false
      xml_accessor :file_availability_descriptions, :as => [Net::Ddex::Xml::V20100712::Ddexc::Description], :from => "FileAvailabilityDescription", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
