#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/text_details_by_territory"
require "net/ddex/xml/v20100712/ddexc/event_date"
require "net/ddex/xml/v20100712/ddexc/musical_work_id"
require "net/ddex/xml/v20100712/ddexc/resource_contained_resource_reference_list"
require "net/ddex/xml/v20100712/ddexc/resource_musical_work_reference_list"
require "net/ddex/xml/v20100712/ddexc/text_id"
require "net/ddex/xml/v20100712/ddexc/text_type"
require "net/ddex/xml/v20100712/ddexc/title"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::Text < Element
  include ROXML


  xml_name "ns1:Text"

      xml_accessor :text_type, :as => Net::Ddex::Xml::V20100712::Ddexc::TextType, :from => "TextType", :required => false
      xml_accessor :artist_related?, :from => "IsArtistRelated", :required => false
      xml_accessor :text_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::TextId], :from => "TextId", :required => false
      xml_accessor :indirect_text_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::MusicalWorkId], :from => "IndirectTextId", :required => false
      xml_accessor :resource_reference, :from => "ResourceReference", :required => true
      xml_accessor :resource_musical_work_reference_list, :as => Net::Ddex::Xml::V20100712::Ddexc::ResourceMusicalWorkReferenceList, :from => "ResourceMusicalWorkReferenceList", :required => false
      xml_accessor :resource_contained_resource_reference_list, :as => Net::Ddex::Xml::V20100712::Ddexc::ResourceContainedResourceReferenceList, :from => "ResourceContainedResourceReferenceList", :required => false
      xml_accessor :titles, :as => [Net::Ddex::Xml::V20100712::Ddexc::Title], :from => "Title", :required => false
      xml_accessor :creation_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "CreationDate", :required => false
      xml_accessor :text_details_by_territories, :as => [DDEX::ERN::V32::TextDetailsByTerritory], :from => "TextDetailsByTerritory", :required => true


  
      xml_accessor :updated?, :from => "@IsUpdated", :required => false
    
  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
