#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/technical_video_details"
require "net/ddex/xml/v20100712/ddexc/av_rating"
require "net/ddex/xml/v20100712/ddexc/c_line"
require "net/ddex/xml/v20100712/ddexc/character"
require "net/ddex/xml/v20100712/ddexc/comment"
require "net/ddex/xml/v20100712/ddexc/courtesy_line"
require "net/ddex/xml/v20100712/ddexc/fulfillment_date"
require "net/ddex/xml/v20100712/ddexc/genre"
require "net/ddex/xml/v20100712/ddexc/host_sound_carrier"
require "net/ddex/xml/v20100712/ddexc/keywords"
require "net/ddex/xml/v20100712/ddexc/parental_warning_type"
require "net/ddex/xml/v20100712/ddexc/sound_recording_details_by_territory"
require "net/ddex/xml/v20100712/ddexc/synopsis"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::VideoDetailsByTerritory < Net::Ddex::Xml::V20100712::Ddexc::SoundRecordingDetailsByTerritory
  include ROXML


  xml_name "ns1:VideoDetailsByTerritory"

      xml_accessor :courtesy_line, :as => Net::Ddex::Xml::V20100712::Ddexc::CourtesyLine, :from => "CourtesyLine", :required => false
      xml_accessor :sequence_number, :from => "SequenceNumber", :required => false
      xml_accessor :host_sound_carriers, :as => [Net::Ddex::Xml::V20100712::Ddexc::HostSoundCarrier], :from => "HostSoundCarrier", :required => false
      xml_accessor :marketing_comment, :as => Net::Ddex::Xml::V20100712::Ddexc::Comment, :from => "MarketingComment", :required => false
      xml_accessor :genres, :as => [Net::Ddex::Xml::V20100712::Ddexc::Genre], :from => "Genre", :required => false
      xml_accessor :parental_warning_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::ParentalWarningType], :from => "ParentalWarningType", :required => false
      xml_accessor :av_ratings, :as => [Net::Ddex::Xml::V20100712::Ddexc::AvRating], :from => "AvRating", :required => false
      xml_accessor :fulfillment_date, :as => Net::Ddex::Xml::V20100712::Ddexc::FulfillmentDate, :from => "FulfillmentDate", :required => false
      xml_accessor :keywords, :as => Net::Ddex::Xml::V20100712::Ddexc::Keywords, :from => "Keywords", :required => false
      xml_accessor :synopsis, :as => Net::Ddex::Xml::V20100712::Ddexc::Synopsis, :from => "Synopsis", :required => false
      xml_accessor :c_lines, :as => [Net::Ddex::Xml::V20100712::Ddexc::CLine], :from => "CLine", :required => false
      xml_accessor :technical_video_details, :as => [DDEX::ERN::V32::TechnicalVideoDetails], :from => "TechnicalVideoDetails", :required => false
      xml_accessor :characters, :as => [Net::Ddex::Xml::V20100712::Ddexc::Character], :from => "Character", :required => false


  

end

end end end
