#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "org/w3c/dom/element"

module Org module W3 module V2000 module V09 module Xmldsig  # :nodoc: all

class Org::W3::V2000::V09::Xmldsig::PGPData < Element
  include ROXML

    setns "ns6", "http://www.w3.org/2000/09/xmldsig#"

  xml_name "ns6:PGPData"

      xml_accessor :pgp_key_id, :from => "ns6:PGPKeyID", :required => false
      xml_accessor :pgp_key_packet, :from => "ns6:PGPKeyPacket", :required => false
      xml_accessor :anies, :as => [Org::W3c::Dom::Element], :from => "anies", :required => false


  

end

end end end end end
