#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "org/w3/v2000/v09/xmldsig/digest_method"
require "org/w3/v2000/v09/xmldsig/transforms"

module Org module W3 module V2000 module V09 module Xmldsig  # :nodoc: all

class Org::W3::V2000::V09::Xmldsig::Reference < Element
  include ROXML

    setns "ns6", "http://www.w3.org/2000/09/xmldsig#"

  xml_name "ns6:Reference"

      xml_accessor :transforms, :as => Org::W3::V2000::V09::Xmldsig::Transforms, :from => "ns6:Transforms", :required => false
      xml_accessor :digest_method, :as => Org::W3::V2000::V09::Xmldsig::DigestMethod, :from => "ns6:DigestMethod", :required => true
      xml_accessor :digest_value, :from => "ns6:DigestValue", :required => true


  
      xml_accessor :id, :from => "@Id", :required => false
    
  
      xml_accessor :uri, :from => "@URI", :required => false
    
  
      xml_accessor :type, :from => "@Type", :required => false
    
  

end

end end end end end
