#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "org/w3/v2000/v09/xmldsig/key_info"
require "org/w3/v2000/v09/xmldsig/object"
require "org/w3/v2000/v09/xmldsig/signature_value"
require "org/w3/v2000/v09/xmldsig/signed_info"

module Org module W3 module V2000 module V09 module Xmldsig  # :nodoc: all

class Org::W3::V2000::V09::Xmldsig::Signature < Element
  include ROXML

    setns "ns6", "http://www.w3.org/2000/09/xmldsig#"

  xml_name "ns6:Signature"

      xml_accessor :signed_info, :as => Org::W3::V2000::V09::Xmldsig::SignedInfo, :from => "ns6:SignedInfo", :required => true
      xml_accessor :signature_value, :as => Org::W3::V2000::V09::Xmldsig::SignatureValue, :from => "ns6:SignatureValue", :required => true
      xml_accessor :key_info, :as => Org::W3::V2000::V09::Xmldsig::KeyInfo, :from => "ns6:KeyInfo", :required => false
      xml_accessor :objects, :as => [Org::W3::V2000::V09::Xmldsig::Object], :from => "ns6:Object", :required => false


  
      xml_accessor :id, :from => "@Id", :required => false
    
  

end

end end end end end
