#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "org/w3/v2000/v09/xmldsig/signature_property"

module Org module W3 module V2000 module V09 module Xmldsig  # :nodoc: all

class Org::W3::V2000::V09::Xmldsig::SignatureProperties < Element
  include ROXML

    setns "ns6", "http://www.w3.org/2000/09/xmldsig#"

  xml_name "ns6:SignatureProperties"

      xml_accessor :signature_properties, :as => [Org::W3::V2000::V09::Xmldsig::SignatureProperty], :from => "ns6:SignatureProperty", :required => true


  
      xml_accessor :id, :from => "@Id", :required => false
    
  

end

end end end end end
