#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module Org module W3 module V2000 module V09 module Xmldsig  # :nodoc: all

class Org::W3::V2000::V09::Xmldsig::X509Data < Element
  include ROXML

    setns "ns6", "http://www.w3.org/2000/09/xmldsig#"

  xml_name "ns6:X509Data"

      xml_accessor :x509_issuer_serials_and_x509_skis_and_x509_subject_names, :as => [], :from => "x509IssuerSerialsAndX509SKISAndX509SubjectNames", :required => false


  

end

end end end end end
