#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module Org module W3 module V2000 module V09 module Xmldsig  # :nodoc: all

class Org::W3::V2000::V09::Xmldsig::X509IssuerSerialType < Element
  include ROXML


  xml_name "ns6:X509IssuerSerialType"

      xml_accessor :x509_issuer_name, :from => "ns6:X509IssuerName", :required => true
      xml_accessor :x509_serial_number, :as => Integer, :from => "ns6:X509SerialNumber", :required => true


  

end

end end end end end
