#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/party_descriptor"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::AdministratingRecordCompany < Net::Ddex::Xml::V20110120::Ddexc::PartyDescriptor
  include ROXML


  xml_name "ns5:AdministratingRecordCompany"



  
      xml_accessor :role, :from => "@Role", :required => true
    
  

end

end end end end end
