#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/collection_type"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::AmountPerCollection < Element
  include ROXML


  xml_name "ns5:AmountPerCollection"

      xml_accessor :amount, :as => Float, :from => "Amount", :required => true
      xml_accessor :collection_type, :as => Net::Ddex::Xml::V20110120::Ddexc::CollectionType, :from => "CollectionType", :required => true


  

end

end end end end end
