#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/collection_collection_reference_list"
require "net/ddex/xml/v20110120/ddexc/collection_details_by_territory"
require "net/ddex/xml/v20110120/ddexc/collection_id"
require "net/ddex/xml/v20110120/ddexc/collection_type"
require "net/ddex/xml/v20110120/ddexc/event_date"
require "net/ddex/xml/v20110120/ddexc/resource_contributor"
require "net/ddex/xml/v20110120/ddexc/title"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::Collection < Element
  include ROXML


  xml_name "ns5:Collection"

      xml_accessor :collection_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::CollectionId], :from => "CollectionId", :required => true
      xml_accessor :collection_types, :as => [Net::Ddex::Xml::V20110120::Ddexc::CollectionType], :from => "CollectionType", :required => false
      xml_accessor :collection_reference, :from => "CollectionReference", :required => true
      xml_accessor :titles, :as => [Net::Ddex::Xml::V20110120::Ddexc::Title], :from => "Title", :required => false
      xml_accessor :contributors, :as => [Net::Ddex::Xml::V20110120::Ddexc::ResourceContributor], :from => "Contributor", :required => false
      xml_accessor :collection_collection_reference_list, :as => Net::Ddex::Xml::V20110120::Ddexc::CollectionCollectionReferenceList, :from => "CollectionCollectionReferenceList", :required => false
      xml_accessor :complete?, :from => "IsComplete", :required => false
      xml_accessor :duration_of_musical_content, :from => "DurationOfMusicalContent", :required => false
      xml_accessor :creation_date, :as => Net::Ddex::Xml::V20110120::Ddexc::EventDate, :from => "CreationDate", :required => false
      xml_accessor :original_release_date, :as => Net::Ddex::Xml::V20110120::Ddexc::EventDate, :from => "OriginalReleaseDate", :required => false
      xml_accessor :original_language, :from => "OriginalLanguage", :required => false
      xml_accessor :collection_details_by_territories, :as => [Net::Ddex::Xml::V20110120::Ddexc::CollectionDetailsByTerritory], :from => "CollectionDetailsByTerritory", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
