#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::CueCreationReference < Element
  include ROXML


  xml_name "ns5:CueCreationReference"

      xml_accessor :cue_resource_reference, :from => "CueResourceReference", :required => false
      xml_accessor :cue_work_reference, :from => "CueWorkReference", :required => false


  

end

end end end end end
