#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/fingerprint_algorithm_type"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::Fingerprint < Element
  include ROXML


  xml_name "ns5:Fingerprint"

      xml_accessor :fingerprint, :from => "Fingerprint", :required => true
      xml_accessor :fingerprint_algorithm_type, :as => Net::Ddex::Xml::V20110120::Ddexc::FingerprintAlgorithmType, :from => "FingerprintAlgorithmType", :required => true
      xml_accessor :fingerprint_algorithm_version, :from => "FingerprintAlgorithmVersion", :required => false
      xml_accessor :fingerprint_algorithm_parameter, :from => "FingerprintAlgorithmParameter", :required => false


  

end

end end end end end
