#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/description"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::Genre < Element
  include ROXML


  xml_name "ns5:Genre"

      xml_accessor :genre_text, :as => Net::Ddex::Xml::V20110120::Ddexc::Description, :from => "GenreText", :required => true
      xml_accessor :sub_genre, :as => Net::Ddex::Xml::V20110120::Ddexc::Description, :from => "SubGenre", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
