#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/administrating_record_company"
require "net/ddex/xml/v20110120/ddexc/artist"
require "net/ddex/xml/v20110120/ddexc/release_id"
require "net/ddex/xml/v20110120/ddexc/rights_agreement_id"
require "net/ddex/xml/v20110120/ddexc/title"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::HostSoundCarrier < Element
  include ROXML


  xml_name "ns5:HostSoundCarrier"

      xml_accessor :release_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseId], :from => "ReleaseId", :required => false
      xml_accessor :rights_agreement_id, :as => Net::Ddex::Xml::V20110120::Ddexc::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :titles, :as => [Net::Ddex::Xml::V20110120::Ddexc::Title], :from => "Title", :required => false
      xml_accessor :display_artists, :as => [Net::Ddex::Xml::V20110120::Ddexc::Artist], :from => "DisplayArtist", :required => false
      xml_accessor :administrating_record_companies, :as => [Net::Ddex::Xml::V20110120::Ddexc::AdministratingRecordCompany], :from => "AdministratingRecordCompany", :required => false
      xml_accessor :track_number, :from => "TrackNumber", :required => false
      xml_accessor :volume_number_in_set, :from => "VolumeNumberInSet", :required => false


  

end

end end end end end
