#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/c_line"
require "net/ddex/xml/v20110120/ddexc/courtesy_line"
require "net/ddex/xml/v20110120/ddexc/description"
require "net/ddex/xml/v20110120/ddexc/event_date"
require "net/ddex/xml/v20110120/ddexc/indirect_resource_contributor"
require "net/ddex/xml/v20110120/ddexc/resource_contributor"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::ImageDetailsByTerritory < Element
  include ROXML


  xml_name "ns5:ImageDetailsByTerritory"

      xml_accessor :excluded_territory_codes, :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :from => "TerritoryCode", :required => false
      xml_accessor :resource_contributors, :as => [Net::Ddex::Xml::V20110120::Ddexc::ResourceContributor], :from => "ResourceContributor", :required => false
      xml_accessor :indirect_resource_contributors, :as => [Net::Ddex::Xml::V20110120::Ddexc::IndirectResourceContributor], :from => "IndirectResourceContributor", :required => false
      xml_accessor :c_lines, :as => [Net::Ddex::Xml::V20110120::Ddexc::CLine], :from => "CLine", :required => false
      xml_accessor :description, :as => Net::Ddex::Xml::V20110120::Ddexc::Description, :from => "Description", :required => false
      xml_accessor :courtesy_line, :as => Net::Ddex::Xml::V20110120::Ddexc::CourtesyLine, :from => "CourtesyLine", :required => false
      xml_accessor :original_resource_release_date, :as => Net::Ddex::Xml::V20110120::Ddexc::EventDate, :from => "OriginalResourceReleaseDate", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
