#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/name"
require "net/ddex/xml/v20110120/ddexc/party_id"
require "net/ddex/xml/v20110120/ddexc/party_name"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::MessagingParty < Element
  include ROXML


  xml_name "ns5:MessagingParty"

      xml_accessor :party_id, :as => Net::Ddex::Xml::V20110120::Ddexc::PartyId, :from => "PartyId", :required => true
      xml_accessor :party_name, :as => Net::Ddex::Xml::V20110120::Ddexc::PartyName, :from => "PartyName", :required => false
      xml_accessor :trading_name, :as => Net::Ddex::Xml::V20110120::Ddexc::Name, :from => "TradingName", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
