#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/name"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::PartyName < Element
  include ROXML


  xml_name "ns5:PartyName"

      xml_accessor :full_name, :as => Net::Ddex::Xml::V20110120::Ddexc::Name, :from => "FullName", :required => true
      xml_accessor :full_name_ascii_transcribed, :from => "FullNameAsciiTranscribed", :required => false
      xml_accessor :full_name_indexed, :as => Net::Ddex::Xml::V20110120::Ddexc::Name, :from => "FullNameIndexed", :required => false
      xml_accessor :names_before_key_name, :as => Net::Ddex::Xml::V20110120::Ddexc::Name, :from => "NamesBeforeKeyName", :required => false
      xml_accessor :key_name, :as => Net::Ddex::Xml::V20110120::Ddexc::Name, :from => "KeyName", :required => false
      xml_accessor :names_after_key_name, :as => Net::Ddex::Xml::V20110120::Ddexc::Name, :from => "NamesAfterKeyName", :required => false
      xml_accessor :abbreviated_name, :as => Net::Ddex::Xml::V20110120::Ddexc::Name, :from => "AbbreviatedName", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
