#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/description"
require "net/ddex/xml/v20110120/ddexc/price"
require "net/ddex/xml/v20110120/ddexc/price_range_type"
require "net/ddex/xml/v20110120/ddexc/price_type"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::PriceInformation < Element
  include ROXML


  xml_name "ns5:PriceInformation"

      xml_accessor :description, :as => Net::Ddex::Xml::V20110120::Ddexc::Description, :from => "Description", :required => false
      xml_accessor :price_range_type, :as => Net::Ddex::Xml::V20110120::Ddexc::PriceRangeType, :from => "PriceRangeType", :required => false
      xml_accessor :price_type, :as => Net::Ddex::Xml::V20110120::Ddexc::PriceType, :from => "PriceType", :required => false
      xml_accessor :wholesale_price_per_unit, :as => Net::Ddex::Xml::V20110120::Ddexc::Price, :from => "WholesalePricePerUnit", :required => false
      xml_accessor :bulk_order_wholesale_price_per_unit, :as => Net::Ddex::Xml::V20110120::Ddexc::Price, :from => "BulkOrderWholesalePricePerUnit", :required => false
      xml_accessor :suggested_retail_price, :as => Net::Ddex::Xml::V20110120::Ddexc::Price, :from => "SuggestedRetailPrice", :required => false


  

end

end end end end end
