#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/event_date"
require "net/ddex/xml/v20110120/ddexc/reference_title"
require "net/ddex/xml/v20110120/ddexc/release_id"
require "net/ddex/xml/v20110120/ddexc/release_relationship_type"
require "net/ddex/xml/v20110120/ddexc/release_summary_details_by_territory"
require "net/ddex/xml/v20110120/ddexc/rights_agreement_id"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::RelatedRelease < Element
  include ROXML


  xml_name "ns5:RelatedRelease"

      xml_accessor :release_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseId], :from => "ReleaseId", :required => true
      xml_accessor :reference_title, :as => Net::Ddex::Xml::V20110120::Ddexc::ReferenceTitle, :from => "ReferenceTitle", :required => false
      xml_accessor :release_summary_details_by_territories, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseSummaryDetailsByTerritory], :from => "ReleaseSummaryDetailsByTerritory", :required => false
      xml_accessor :rights_agreement_id, :as => Net::Ddex::Xml::V20110120::Ddexc::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :release_relationship_type, :as => Net::Ddex::Xml::V20110120::Ddexc::ReleaseRelationshipType, :from => "ReleaseRelationshipType", :required => true
      xml_accessor :release_date, :as => Net::Ddex::Xml::V20110120::Ddexc::EventDate, :from => "ReleaseDate", :required => false
      xml_accessor :original_release_date, :as => Net::Ddex::Xml::V20110120::Ddexc::EventDate, :from => "OriginalReleaseDate", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
