#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/administrating_record_company"
require "net/ddex/xml/v20110120/ddexc/artist"
require "net/ddex/xml/v20110120/ddexc/related_release"
require "net/ddex/xml/v20110120/ddexc/release_summary_details_by_territory"
require "net/ddex/xml/v20110120/ddexc/release_type"
require "net/ddex/xml/v20110120/ddexc/title"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::ReleaseDetailsByTerritory < Net::Ddex::Xml::V20110120::Ddexc::ReleaseSummaryDetailsByTerritory
  include ROXML


  xml_name "ns5:ReleaseDetailsByTerritory"

      xml_accessor :titles, :as => [Net::Ddex::Xml::V20110120::Ddexc::Title], :from => "Title", :required => false
      xml_accessor :display_artists, :as => [Net::Ddex::Xml::V20110120::Ddexc::Artist], :from => "DisplayArtist", :required => true
      xml_accessor :multi_artist_compilation?, :from => "IsMultiArtistCompilation", :required => false
      xml_accessor :administrating_record_companies, :as => [Net::Ddex::Xml::V20110120::Ddexc::AdministratingRecordCompany], :from => "AdministratingRecordCompany", :required => false
      xml_accessor :release_types, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseType], :from => "ReleaseType", :required => false
      xml_accessor :related_releases, :as => [Net::Ddex::Xml::V20110120::Ddexc::RelatedRelease], :from => "RelatedRelease", :required => false


  

end

end end end end end
