#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/c_line"
require "net/ddex/xml/v20110120/ddexc/p_line"
require "net/ddex/xml/v20110120/ddexc/reference_title"
require "net/ddex/xml/v20110120/ddexc/release_details_by_territory"
require "net/ddex/xml/v20110120/ddexc/release_id"
require "net/ddex/xml/v20110120/ddexc/release_resource_reference_list"
require "net/ddex/xml/v20110120/ddexc/release_type"
require "net/ddex/xml/v20110120/ddexc/rights_agreement_id"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::Release < Element
  include ROXML


  xml_name "ns5:Release"

      xml_accessor :release_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseId], :from => "ReleaseId", :required => true
      xml_accessor :reference_title, :as => Net::Ddex::Xml::V20110120::Ddexc::ReferenceTitle, :from => "ReferenceTitle", :required => true
      xml_accessor :release_resource_reference_list, :as => Net::Ddex::Xml::V20110120::Ddexc::ReleaseResourceReferenceList, :from => "ReleaseResourceReferenceList", :required => false
      xml_accessor :release_types, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseType], :from => "ReleaseType", :required => false
      xml_accessor :release_details_by_territories, :as => [Net::Ddex::Xml::V20110120::Ddexc::ReleaseDetailsByTerritory], :from => "ReleaseDetailsByTerritory", :required => true
      xml_accessor :duration, :from => "Duration", :required => false
      xml_accessor :rights_agreement_id, :as => Net::Ddex::Xml::V20110120::Ddexc::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :p_lines, :as => [Net::Ddex::Xml::V20110120::Ddexc::PLine], :from => "PLine", :required => false
      xml_accessor :c_lines, :as => [Net::Ddex::Xml::V20110120::Ddexc::CLine], :from => "CLine", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
