#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/resource_contained_resource_reference"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::ResourceContainedResourceReferenceList < Element
  include ROXML


  xml_name "ns5:ResourceContainedResourceReferenceList"

      xml_accessor :resource_contained_resource_references, :as => [Net::Ddex::Xml::V20110120::Ddexc::ResourceContainedResourceReference], :from => "ResourceContainedResourceReference", :required => true


  

end

end end end end end
