#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/reason"
require "net/ddex/xml/v20110120/ddexc/reason_type"
require "net/ddex/xml/v20110120/ddexc/release_id"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::SalesReportingProxyReleaseId < Element
  include ROXML


  xml_name "ns5:SalesReportingProxyReleaseId"

      xml_accessor :release_id, :as => Net::Ddex::Xml::V20110120::Ddexc::ReleaseId, :from => "ReleaseId", :required => true
      xml_accessor :reason, :as => Net::Ddex::Xml::V20110120::Ddexc::Reason, :from => "Reason", :required => false
      xml_accessor :reason_type, :as => Net::Ddex::Xml::V20110120::Ddexc::ReasonType, :from => "ReasonType", :required => true


  

end

end end end end end
