#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/event_date"
require "net/ddex/xml/v20110120/ddexc/musical_work_id"
require "net/ddex/xml/v20110120/ddexc/reference_title"
require "net/ddex/xml/v20110120/ddexc/resource_contained_resource_reference_list"
require "net/ddex/xml/v20110120/ddexc/resource_musical_work_reference_list"
require "net/ddex/xml/v20110120/ddexc/rights_agreement_id"
require "net/ddex/xml/v20110120/ddexc/sheet_music_details_by_territory"
require "net/ddex/xml/v20110120/ddexc/sheet_music_id"
require "net/ddex/xml/v20110120/ddexc/sheet_music_type"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::SheetMusic < Element
  include ROXML


  xml_name "ns5:SheetMusic"

      xml_accessor :sheet_music_type, :as => Net::Ddex::Xml::V20110120::Ddexc::SheetMusicType, :from => "SheetMusicType", :required => false
      xml_accessor :artist_related?, :from => "IsArtistRelated", :required => false
      xml_accessor :sheet_music_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::SheetMusicId], :from => "SheetMusicId", :required => true
      xml_accessor :indirect_sheet_music_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::MusicalWorkId], :from => "IndirectSheetMusicId", :required => false
      xml_accessor :resource_reference, :from => "ResourceReference", :required => true
      xml_accessor :language_of_lyrics, :from => "LanguageOfLyrics", :required => false
      xml_accessor :rights_agreement_id, :as => Net::Ddex::Xml::V20110120::Ddexc::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :resource_musical_work_reference_list, :as => Net::Ddex::Xml::V20110120::Ddexc::ResourceMusicalWorkReferenceList, :from => "ResourceMusicalWorkReferenceList", :required => false
      xml_accessor :resource_contained_resource_reference_list, :as => Net::Ddex::Xml::V20110120::Ddexc::ResourceContainedResourceReferenceList, :from => "ResourceContainedResourceReferenceList", :required => false
      xml_accessor :reference_title, :as => Net::Ddex::Xml::V20110120::Ddexc::ReferenceTitle, :from => "ReferenceTitle", :required => true
      xml_accessor :creation_date, :as => Net::Ddex::Xml::V20110120::Ddexc::EventDate, :from => "CreationDate", :required => false
      xml_accessor :sheet_music_details_by_territories, :as => [Net::Ddex::Xml::V20110120::Ddexc::SheetMusicDetailsByTerritory], :from => "SheetMusicDetailsByTerritory", :required => true


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
