#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/event_date"
require "net/ddex/xml/v20110120/ddexc/musical_work_id"
require "net/ddex/xml/v20110120/ddexc/resource_contained_resource_reference_list"
require "net/ddex/xml/v20110120/ddexc/resource_musical_work_reference_list"
require "net/ddex/xml/v20110120/ddexc/text_details_by_territory"
require "net/ddex/xml/v20110120/ddexc/text_id"
require "net/ddex/xml/v20110120/ddexc/text_type"
require "net/ddex/xml/v20110120/ddexc/title"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::Text < Element
  include ROXML


  xml_name "ns5:Text"

      xml_accessor :text_type, :as => Net::Ddex::Xml::V20110120::Ddexc::TextType, :from => "TextType", :required => false
      xml_accessor :artist_related?, :from => "IsArtistRelated", :required => false
      xml_accessor :text_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::TextId], :from => "TextId", :required => false
      xml_accessor :indirect_text_ids, :as => [Net::Ddex::Xml::V20110120::Ddexc::MusicalWorkId], :from => "IndirectTextId", :required => false
      xml_accessor :resource_reference, :from => "ResourceReference", :required => true
      xml_accessor :resource_musical_work_reference_list, :as => Net::Ddex::Xml::V20110120::Ddexc::ResourceMusicalWorkReferenceList, :from => "ResourceMusicalWorkReferenceList", :required => false
      xml_accessor :resource_contained_resource_reference_list, :as => Net::Ddex::Xml::V20110120::Ddexc::ResourceContainedResourceReferenceList, :from => "ResourceContainedResourceReferenceList", :required => false
      xml_accessor :titles, :as => [Net::Ddex::Xml::V20110120::Ddexc::Title], :from => "Title", :required => false
      xml_accessor :creation_date, :as => Net::Ddex::Xml::V20110120::Ddexc::EventDate, :from => "CreationDate", :required => false
      xml_accessor :text_details_by_territories, :as => [Net::Ddex::Xml::V20110120::Ddexc::TextDetailsByTerritory], :from => "TextDetailsByTerritory", :required => true


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
