#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20110120/ddexc/c_line"
require "net/ddex/xml/v20110120/ddexc/sound_recording_details_by_territory"

module Net module Ddex module Xml module V20110120 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20110120::Ddexc::VideoDetailsByTerritory < Net::Ddex::Xml::V20110120::Ddexc::SoundRecordingDetailsByTerritory
  include ROXML


  xml_name "ns5:VideoDetailsByTerritory"

      xml_accessor :c_lines, :as => [Net::Ddex::Xml::V20110120::Ddexc::CLine], :from => "CLine", :required => false


  

end

end end end end end
