#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/party_descriptor"
require "net/ddex/xml/v20100712/ddexc/resource_contributor"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::Character < Net::Ddex::Xml::V20100712::Ddexc::PartyDescriptor
  include ROXML


  xml_name "ns2:Character"

      xml_accessor :resource_contributor, :as => Net::Ddex::Xml::V20100712::Ddexc::ResourceContributor, :from => "ResourceContributor", :required => false


  

      xml_accessor :sequence_number, :as => Integer, :from => "@SequenceNumber", :required => false
    
  

end

end end end end end
