#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/related_release"
require "net/ddex/xml/v20100712/ddexc/release_summary"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::ContainedReleaseSummary < Net::Ddex::Xml::V20100712::Ddexc::ReleaseSummary
  include ROXML


  xml_name "ns2:ContainedReleaseSummary"

      xml_accessor :related_releases, :as => [Net::Ddex::Xml::V20100712::Ddexc::RelatedRelease], :from => "RelatedRelease", :required => false


  

end

end end end end end
