#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/name"
require "net/ddex/xml/v20100712/ddexc/party_descriptor"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::DSP < Net::Ddex::Xml::V20100712::Ddexc::PartyDescriptor
  include ROXML


  xml_name "ns2:DSP"

      xml_accessor :trading_name, :as => Net::Ddex::Xml::V20100712::Ddexc::Name, :from => "TradingName", :required => false
      xml_accessor :urls, :as => [], :from => "URL", :required => false
      xml_accessor :territory_code, :from => "TerritoryCode", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
