#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::FulfillmentDate < Element
  include ROXML


  xml_name "ns2:FulfillmentDate"

      xml_accessor :fulfillment_date, :as => Date, :from => "FulfillmentDate", :required => true
      xml_accessor :resource_release_references, :as => [], :from => "ResourceReleaseReference", :required => false


  

end

end end end end end
