#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/message_audit_trail_event"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::MessageAuditTrail < Element
  include ROXML


  xml_name "ns2:MessageAuditTrail"

      xml_accessor :message_audit_trail_events, :as => [Net::Ddex::Xml::V20100712::Ddexc::MessageAuditTrailEvent], :from => "MessageAuditTrailEvent", :required => true


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
