#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/musical_work_contributor"
require "net/ddex/xml/v20100712/ddexc/musical_work_details_by_territory"
require "net/ddex/xml/v20100712/ddexc/musical_work_id"
require "net/ddex/xml/v20100712/ddexc/musical_work_type"
require "net/ddex/xml/v20100712/ddexc/reference_title"
require "net/ddex/xml/v20100712/ddexc/right_share"
require "net/ddex/xml/v20100712/ddexc/rights_agreement_id"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::MusicalWork < Element
  include ROXML


  xml_name "ns2:MusicalWork"

      xml_accessor :musical_work_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::MusicalWorkId], :from => "MusicalWorkId", :required => true
      xml_accessor :musical_work_reference, :from => "MusicalWorkReference", :required => true
      xml_accessor :reference_titles, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReferenceTitle], :from => "ReferenceTitle", :required => true
      xml_accessor :rights_agreement_id, :as => Net::Ddex::Xml::V20100712::Ddexc::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :musical_work_contributors, :as => [Net::Ddex::Xml::V20100712::Ddexc::MusicalWorkContributor], :from => "MusicalWorkContributor", :required => true
      xml_accessor :musical_work_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::MusicalWorkType], :from => "MusicalWorkType", :required => false
      xml_accessor :right_shares, :as => [Net::Ddex::Xml::V20100712::Ddexc::RightShare], :from => "RightShare", :required => false
      xml_accessor :musical_work_details_by_territories, :as => [Net::Ddex::Xml::V20100712::Ddexc::MusicalWorkDetailsByTerritory], :from => "MusicalWorkDetailsByTerritory", :required => false


  
      xml_accessor :updated?, :from => "@IsUpdated", :required => false
    
  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
