#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/musical_work_contributor_role"
require "net/ddex/xml/v20100712/ddexc/party_descriptor"
require "net/ddex/xml/v20100712/ddexc/society_affiliation"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::MusicalWorkContributor < Net::Ddex::Xml::V20100712::Ddexc::PartyDescriptor
  include ROXML


  xml_name "ns2:MusicalWorkContributor"

      xml_accessor :musical_work_contributor_roles, :as => [Net::Ddex::Xml::V20100712::Ddexc::MusicalWorkContributorRole], :from => "MusicalWorkContributorRole", :required => false
      xml_accessor :society_affiliations, :as => [Net::Ddex::Xml::V20100712::Ddexc::SocietyAffiliation], :from => "SocietyAffiliation", :required => false


  

      xml_accessor :sequence_number, :as => Integer, :from => "@SequenceNumber", :required => false
    
  

end

end end end end end
