#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:11 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/event_date"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::Period < Element
  include ROXML


  xml_name "ns2:Period"

      xml_accessor :start_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "StartDate", :required => false
      xml_accessor :end_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "EndDate", :required => false


  

end

end end end end end
