#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/administrating_record_company"
require "net/ddex/xml/v20100712/ddexc/display_artist"
require "net/ddex/xml/v20100712/ddexc/related_release"
require "net/ddex/xml/v20100712/ddexc/release_summary_details_by_territory"
require "net/ddex/xml/v20100712/ddexc/release_type"
require "net/ddex/xml/v20100712/ddexc/title"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::ReleaseDetailsByTerritory < Net::Ddex::Xml::V20100712::Ddexc::ReleaseSummaryDetailsByTerritory
  include ROXML


  xml_name "ns2:ReleaseDetailsByTerritory"

      xml_accessor :titles, :as => [Net::Ddex::Xml::V20100712::Ddexc::Title], :from => "Title", :required => false
      xml_accessor :display_artists, :as => [Net::Ddex::Xml::V20100712::Ddexc::DisplayArtist], :from => "DisplayArtist", :required => true
      xml_accessor :multi_artist_compilation?, :from => "IsMultiArtistCompilation", :required => false
      xml_accessor :administrating_record_companies, :as => [Net::Ddex::Xml::V20100712::Ddexc::AdministratingRecordCompany], :from => "AdministratingRecordCompany", :required => false
      xml_accessor :release_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReleaseType], :from => "ReleaseType", :required => false
      xml_accessor :related_releases, :as => [Net::Ddex::Xml::V20100712::Ddexc::RelatedRelease], :from => "RelatedRelease", :required => false


  

end

end end end end end
