#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/resource_musical_work_reference"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::ResourceMusicalWorkReferenceList < Element
  include ROXML


  xml_name "ns2:ResourceMusicalWorkReferenceList"

      xml_accessor :resource_musical_work_references, :as => [Net::Ddex::Xml::V20100712::Ddexc::ResourceMusicalWorkReference], :from => "ResourceMusicalWorkReference", :required => true


  

end

end end end end end
