#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/carrier_type"
require "net/ddex/xml/v20100712/ddexc/commercial_model_type"
require "net/ddex/xml/v20100712/ddexc/distribution_channel_type"
require "net/ddex/xml/v20100712/ddexc/period"
require "net/ddex/xml/v20100712/ddexc/right_share_creation_reference_list"
require "net/ddex/xml/v20100712/ddexc/rights_agreement_id"
require "net/ddex/xml/v20100712/ddexc/rights_controller"
require "net/ddex/xml/v20100712/ddexc/rights_type"
require "net/ddex/xml/v20100712/ddexc/tariff_reference"
require "net/ddex/xml/v20100712/ddexc/use_type"
require "net/ddex/xml/v20100712/ddexc/user_interface_type"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::RightShare < Element
  include ROXML


  xml_name "ns2:RightShare"

      xml_accessor :right_share_id, :as => Net::Ddex::Xml::V20100712::Ddexc::RightsAgreementId, :from => "RightShareId", :required => false
      xml_accessor :right_share_reference, :from => "RightShareReference", :required => true
      xml_accessor :right_share_creation_reference_list, :as => Net::Ddex::Xml::V20100712::Ddexc::RightShareCreationReferenceList, :from => "RightShareCreationReferenceList", :required => false
      xml_accessor :excluded_territory_codes, :as => [], :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :as => [], :from => "TerritoryCode", :required => false
      xml_accessor :rights_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::RightsType], :from => "RightsType", :required => false
      xml_accessor :use_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::UseType], :from => "UseType", :required => false
      xml_accessor :user_interface_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::UserInterfaceType], :from => "UserInterfaceType", :required => false
      xml_accessor :distribution_channel_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::DistributionChannelType], :from => "DistributionChannelType", :required => false
      xml_accessor :carrier_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::CarrierType], :from => "CarrierType", :required => false
      xml_accessor :commercial_model_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::CommercialModelType], :from => "CommercialModelType", :required => false
      xml_accessor :musical_work_rights_claim_types, :as => [], :from => "MusicalWorkRightsClaimType", :required => false
      xml_accessor :rights_controllers, :as => [Net::Ddex::Xml::V20100712::Ddexc::RightsController], :from => "RightsController", :required => false
      xml_accessor :validity_period, :as => Net::Ddex::Xml::V20100712::Ddexc::Period, :from => "ValidityPeriod", :required => true
      xml_accessor :percentage_rate, :from => "PercentageRate", :required => false
      xml_accessor :percentage_unknown?, :from => "PercentageUnknown", :required => false
      xml_accessor :tariff_reference, :as => Net::Ddex::Xml::V20100712::Ddexc::TariffReference, :from => "TariffReference", :required => false
      xml_accessor :license_status, :from => "LicenseStatus", :required => false
      xml_accessor :has_first_license_refusal?, :from => "HasFirstLicenseRefusal", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
