#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::RightShareCreationReferenceList < Element
  include ROXML


  xml_name "ns2:RightShareCreationReferenceList"

      xml_accessor :right_share_work_references, :as => [], :from => "RightShareWorkReference", :required => false
      xml_accessor :right_share_resource_references, :as => [], :from => "RightShareResourceReference", :required => false
      xml_accessor :right_share_release_references, :as => [], :from => "RightShareReleaseReference", :required => false


  

end

end end end end end
