#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/artist_role"
require "net/ddex/xml/v20100712/ddexc/simple_profile_party_descriptor"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::SimpleProfileDisplayArtist < Net::Ddex::Xml::V20100712::Ddexc::SimpleProfilePartyDescriptor
  include ROXML


  xml_name "ns2:SimpleProfileDisplayArtist"

      xml_accessor :artist_roles, :as => [Net::Ddex::Xml::V20100712::Ddexc::ArtistRole], :from => "ArtistRole", :required => false


  

      xml_accessor :sequence_number, :as => Integer, :from => "@SequenceNumber", :required => false
    
  

end

end end end end end
