#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/comment"
require "net/ddex/xml/v20100712/ddexc/simple_profile_messaging_party"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::SimpleProfileMessageHeader < Element
  include ROXML


  xml_name "ns2:SimpleProfileMessageHeader"

      xml_accessor :message_thread_id, :from => "MessageThreadId", :required => true
      xml_accessor :message_id, :from => "MessageId", :required => true
      xml_accessor :message_file_name, :from => "MessageFileName", :required => false
      xml_accessor :message_sender, :as => Net::Ddex::Xml::V20100712::Ddexc::SimpleProfileMessagingParty, :from => "MessageSender", :required => true
      xml_accessor :message_recipient, :as => Net::Ddex::Xml::V20100712::Ddexc::SimpleProfileMessagingParty, :from => "MessageRecipient", :required => true
      xml_accessor :message_created_date_time, :as => DateTime, :from => "MessageCreatedDateTime", :required => true
      xml_accessor :comment, :as => Net::Ddex::Xml::V20100712::Ddexc::Comment, :from => "Comment", :required => false
      xml_accessor :message_control_type, :from => "MessageControlType", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end
