#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/party_id"
require "net/ddex/xml/v20100712/ddexc/simple_profile_party_name"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::SimpleProfilePartyDescriptor < Element
  include ROXML


  xml_name "ns2:SimpleProfilePartyDescriptor"

      xml_accessor :party_name, :as => Net::Ddex::Xml::V20100712::Ddexc::SimpleProfilePartyName, :from => "PartyName", :required => false
      xml_accessor :party_id, :as => Net::Ddex::Xml::V20100712::Ddexc::PartyId, :from => "PartyId", :required => false


  

end

end end end end end
