#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/bit_rate"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::TechnicalInstantiation < Element
  include ROXML


  xml_name "ns2:TechnicalInstantiation"

      xml_accessor :drm_enforcement_type, :from => "DrmEnforcementType", :required => false
      xml_accessor :video_definition_type, :from => "VideoDefinitionType", :required => false
      xml_accessor :coding_type, :from => "CodingType", :required => false
      xml_accessor :bit_rate, :as => Net::Ddex::Xml::V20100712::Ddexc::BitRate, :from => "BitRate", :required => false


  

end

end end end end end
