#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/release_type"
require "net/ddex/xml/v20100712/ddexc/rights_type"
require "net/ddex/xml/v20100712/ddexc/royalty_amount"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::TotalRoyaltyAmount < Element
  include ROXML


  xml_name "ns2:TotalRoyaltyAmount"

      xml_accessor :release_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReleaseType], :from => "ReleaseType", :required => false
      xml_accessor :rights_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::RightsType], :from => "RightsType", :required => false
      xml_accessor :royalty_amount, :as => Net::Ddex::Xml::V20100712::Ddexc::RoyaltyAmount, :from => "RoyaltyAmount", :required => true


  

end

end end end end end
