#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/carrier_type"
require "net/ddex/xml/v20100712/ddexc/distribution_channel_type"
require "net/ddex/xml/v20100712/ddexc/technical_instantiation"
require "net/ddex/xml/v20100712/ddexc/use_type"
require "net/ddex/xml/v20100712/ddexc/user_interface_type"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::Usage < Element
  include ROXML


  xml_name "ns2:Usage"

      xml_accessor :use_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::UseType], :from => "UseType", :required => true
      xml_accessor :user_interface_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::UserInterfaceType], :from => "UserInterfaceType", :required => false
      xml_accessor :distribution_channel_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::DistributionChannelType], :from => "DistributionChannelType", :required => false
      xml_accessor :carrier_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::CarrierType], :from => "CarrierType", :required => false
      xml_accessor :technical_instantiation, :as => Net::Ddex::Xml::V20100712::Ddexc::TechnicalInstantiation, :from => "TechnicalInstantiation", :required => false
      xml_accessor :number_of_usages, :as => Integer, :from => "NumberOfUsages", :required => false


  

end

end end end end end
