#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-06-17 12:39:12 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/name"

module Net module Ddex module Xml module V20100712 module Ddexc  # :nodoc: all

class Net::Ddex::Xml::V20100712::Ddexc::WebPage < Element
  include ROXML


  xml_name "ns2:WebPage"

      xml_accessor :page_name, :as => Net::Ddex::Xml::V20100712::Ddexc::Name, :from => "PageName", :required => false
      xml_accessor :url, :from => "URL", :required => false
      xml_accessor :user_name, :from => "UserName", :required => false
      xml_accessor :password, :from => "Password", :required => false


  

end

end end end end end
